django_orm_nauka/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from django.conf.urls.static import static
from django.conf import settings

app_name = 'home'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('orm/', views.form),
    path('', views.index),
    path('klienci/', include('orm.urls')),
    path('users_app/', include('users_app.urls')),
    path('', include('order.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

order/urls.py
from django.urls import path
from .views import zlecenie

app_name = 'zlecenie'

urlpatterns = [
    path('zlecenie', zlecenie, name='zlecenie'),
]

orm/urls.py
from django.urls import path
from . import views

app_name = 'orm'

urlpatterns = [
    path('', views.client_list, name='client_list'),
    path('new-client', views.client_new, name='new-client'),
    path('client/<int:id>/<slug:slug>/', views.client_page, name='client_page'),
    path('client/<int:id>/<slug:slug>/edit/', views.edit_client, name='edit_client'),
    path('client/<int:id>/<slug:slug>/delete', views.delete_client, name='delete_client'),
    path('search/', views.search_client, name='search_client'),
]

users_app/urls.py
from django.urls import path
from . import views

app_name = 'users_app'

urlpatterns = [
    path('register/', views.register_view, name='register'),
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),
]

order/models.py
from django.db import models
from django.contrib.auth.models import User
import datetime
from orm.models import Client

# Create your models here.


class Order(models.Model):
    ORDER_CHOICES = [
        ('wegiel', 'Węgiel'),
        ('koks', 'Koks'),
        ('biomasa', 'Biomasa'),
    ]

    badany_obiekt = models.CharField(max_length=10, choices=ORDER_CHOICES)
    client = models.ForeignKey(Client, on_delete=models.CASCADE)
    opis = models.TextField()
    date = models.DateField(default=datetime.date.today, null=True, blank=True)

    def __str__(self):
        return f'{self.id} - {self.badany_obiekt}'

orm/models.py
from django.db import models
from django.contrib.auth.models import User


# Create your models here.

class Client(models.Model):
    name = models.CharField(max_length=50)
    address = models.TextField()
    slug = models.SlugField()
    date = models.DateTimeField(auto_now_add=True)
    banner = models.ImageField(default='aaa.png', blank=True)
    author = models.ForeignKey(User,  on_delete=models.SET_NULL, null=True, blank=True, default=None)

    def __str__(self):
        return f'{self.name} - {self.slug}'

users_app/models.py
from django.db import models

# Create your models here.

order/forms.py
from django import forms
from .models import Order

class OrderForm(forms.ModelForm):
    class Meta:
        model = Order
        fields = ['badany_obiekt', 'client', 'opis', 'date']

orm/forms.py
from django import forms
from . import models

class CreateClient(forms.ModelForm):
    class Meta:
        model = models.Client
        fields = ['name', 'address', 'slug', 'banner']

class ClientForm(forms.ModelForm):  # wiem, powtarza się
    class Meta:
        model = models.Client
        fields = ['name', 'address', 'author', 'banner']


class ClientSearchForm(forms.Form):
    query = forms.CharField(label='Wyszukaj klienta', max_length=200)

django_orm_nauka/views.py
# from django.http import HttpResponse
from django.shortcuts import render
def index(request):
    # return HttpResponse("Hello, Django! Index page.")
    return render(request, 'index.html')

def form(request):
    # return HttpResponse("Orm page. Page with forms to add client.")
    return render(request, 'orm.html')

order/views.py
from django.shortcuts import render, redirect
from .forms import OrderForm

# Create your views here.



def zlecenie(request):
    if request.method == 'POST':
        form = OrderForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('/')  # Zamień 'success_url' na odpowiednią nazwę ścieżki
    else:
        form = OrderForm()

    return render(request, 'order/zlecenie.html', {'form': form})

orm/views.py
from django.shortcuts import render, get_object_or_404, redirect
from .models import Client
from django.contrib.auth.decorators import login_required
from . import forms
from django.http import HttpResponse


# Create your views here.
@login_required(login_url='/users_app/login')
def client_list(request):
    clients = Client.objects.all().order_by('name')
    return render(request, 'klienci/client_list.html', {"clients": clients})

def client_page(request, id, slug):
    one_client = Client.objects.get(id=id, slug=slug)
    return render(request, 'klienci/client_page.html', {"client": one_client})

@login_required(login_url='/users_app/login')
def client_new(request):
    if request.method == 'POST':
        form = forms.CreateClient(request.POST, request.FILES)
        if form.is_valid():
            new_client = form.save(commit=False)
            new_client.author = request.user
            new_client.save()
            return redirect('orm:client_list')
    else:
        form = forms.CreateClient()
    return render(request, 'klienci/client_new.html', {"form": form})

# @login_required(login_url='/users_app/login')
def edit_client(request, id, slug):
    # return HttpResponse("Hello, Django! Index page.")

    client = Client.objects.get(id=id, slug=slug)
    print('1')
    if request.method == 'POST':
        form = forms.ClientForm(request.POST, request.FILES, instance=client)
        print('2')
        if form.is_valid():
            form.save()
            return redirect('orm:client_list')
            print('3')
        else:
            form = forms.ClientForm(instance=client)
            print('4')
    else:
      form = forms.ClientForm(instance=client)
      print('5')
      return render(request, 'klienci/edit_client.html', {'form': form, 'client': client})
    return render(request, 'klienci/edit_client.html', {'form': form, 'client': client})

def delete_client(request, id, slug):
    client = Client.objects.get(id=id, slug=slug)
    if request.method == 'POST':
        client.delete()
        return redirect('orm:client_list')
    return redirect('orm:client_detail', id=id)

def search_client(request):
    form = forms.ClientSearchForm(request.GET)
    clients = None

    if 'query' in request.GET:
        form = forms.ClientSearchForm(request.GET)
        if form.is_valid():
            query = form.cleaned_data['query']
            clients = Client.objects.filter(name__icontains=query)
    return render(request, 'klienci/search_results.html', {"form": form, "clients": clients})

users_app/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth import login, logout

# Create your views here.
def register_view(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            login(request, form.save())
            return redirect('/') # wracamy do strony jakiejs
    else:
        form = UserCreationForm()
    return render(request, 'users/register.html', {'form': form})

def login_view(request):
    if request.method == 'POST':
        form = AuthenticationForm(data=request.POST)
        if form.is_valid():
            login(request, form.get_user())
            if 'next' in request.POST:
                return redirect(request.POST.get('next'))
            else:
                return redirect('/')
    else:
        form = AuthenticationForm(request, data=request.POST)
    return render(request, 'users/login.html', {'form': form})

def logout_view(request):
    if request.method == 'POST':
        logout(request)
        return redirect('/')

order/templates/order/zlecenie.html
{% extends 'base.html' %}
{% load static %}
{% load django_bootstrap5 %}

{% block title %}
   Zlecenie wykonania oznaczenia
{% endblock %}

{% block content %}
    <div class="col-md-7 col-lg-8 mt-3">
        <h1 class="mb-3">
            Zlecenie wykonania oznaczenia
        </h1>
        <form class="form-with-validation" method="post">

            {% csrf_token %}
            {% bootstrap_form form %}


            {% bootstrap_button button_type="submit" content="Zapisz" %}
        </form>
    </div>
    <a href="/klienci" class="homepage"><img src="{% static 'images/back-arrow.png' %}"></a>
{% endblock %}

{#<!DOCTYPE html>#}
{#<html>#}
{#<head>#}
{#    <title>Badany Obiekt Form</title>#}
{#</head>#}
{#<body>#}
{#    <h1>Formularz Badanego Obiektu</h1>#}
{#    <form method="post">#}
{#        {% csrf_token %}#}
{#        {{ form.as_p }}#}
{#        <button type="submit">Zapisz</button>#}
{#    </form>#}
{#</body>#}
{#</html>#}

orm/templates/klienci/client_list.html
{% extends 'base.html' %}
{% load static %}
{% load django_bootstrap5 %}

{% block title %}
    Klienci
{% endblock %}

{% block content %}
    <h1>Lista Klientów</h1>
    <!-- Dodanie sekcji wyszukiwania, jeśli potrzebujesz -->
<div class="search">
    <form method="GET" action="{% url 'orm:search_client' %}">
        {{ form.as_p }}
{#          <button type="submit" class="button-33">Wyszukaj Klienta</button>#}
        <div class="mb-3">{% bootstrap_button button_type="submit" content="Wyszukaj Klienta" %}</div>
    </form>
</div>

    <section>
    <div >
         <table class="table table-striped table-hover table-bordered">
            <thead>
                <tr  class="table-success">
                    <th scope="col">ID Klienta</th>
                    <th scope="col">Nazwa Klienta</th>

                    <th>Adres</th>
                    <th>Dodany przez użytkownika</th>
                </tr>
            </thead>
            <tbody class="table-group-divider">
                {% for client in clients %}
                    <tr>
                        <th scope="col">
                            {{ client.id }}
                        </th>
                        <td>
                            <a href="{% url 'orm:client_page'  id=client.id slug=client.slug %}">
                                {{ client.name }}
                            </a>
                        </td>
                         
                        <td>{{ client.address }}</td>
                        <td>{{ client.author }}</td>
                    </tr>
                {% endfor %}
            </tbody>
         </table>
    </div>
    </section>
    <a href="/" class="homepage"><img src="{% static 'images/back-arrow.png' %}"></a>
{% endblock %}

orm/templates/klienci/client_new.html
{% extends 'base.html' %}
{% load static %}
{% load django_bootstrap5 %}



{% block title %}
   Nowy Klient
{% endblock %}

{% block content %}
    <div class="col-md-7 col-lg-8 mt-3">
        <h1 class="mb-3">
            Nowy Klient
        </h1>
        <form class="form-with-validation " action="{% url 'orm:new-client' %}" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {% bootstrap_form form %}

{#            <button class="form-submit button-33">Dodaj Klienta</button>#}
            {% bootstrap_button button_type="submit" content="Dodaj Klienta" %}
        </form>
    </div>
    <a href="/klienci" class="homepage"><img src="{% static 'images/back-arrow.png' %}"></a>
{% endblock %}

orm/templates/klienci/client_page.html
{% extends 'base.html' %}
{% load static %}
{% load django_bootstrap5 %}


{% block title %}
   {{ client.name }}
{% endblock %}

{% block content %}
    <div class="client">
        <div class="mt-3">
            <a href="{% url 'orm:edit_client' id=client.id slug=client.slug %}" class="form-submit button-33">{% bootstrap_button button_type="button" content="Edytuj" %}</a>

            <!-- Delete Button Form -->
        <form action="{% url 'orm:delete_client' id=client.id slug=client.slug %}" method="post" style="display: inline" onsubmit="return confirm('Are you sure you want to delete this client?');">
            {% csrf_token %}
{#            <button type="submit" class="form-submit button-33">Usuń</button>#}
            {% bootstrap_button button_type="submit" content="Usuń" %}
        </form>
        </div>
        <img
            class="banner"
            src="{{ client.banner.url }}"
            />
        <h1>{{ client.name }}</h1>
        <p>{{ client.address }}</p>
        <p>{{ client.author }}</p>


    </div>

    <a href="/klienci" class="homepage"><img src="{% static 'images/back-arrow.png' %}"></a>

{% endblock %}

orm/templates/klienci/edit_client.html
{% extends 'base.html' %}
{% load static %}
{% load django_bootstrap5 %}

{% block title %}
    Edytuj klienta: {{ client.name }}
{% endblock %}

{% block content %}
  <h1>Edytuj klienta: {{ client.name }}</h1>
  <form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
{#    <button type="submit">Zapisz zmiany</button>#}
    {% bootstrap_button button_type="submit" content="Zapisz zmiany" %}
  </form><br>
  <a href="{% url 'orm:client_page'  id=client.id slug=client.slug %}">{% bootstrap_button content='Anuluj' %}</a>
{% endblock %}

orm/templates/klienci/search_results.html
{% extends 'base.html' %}
{% load static %}
{% load django_bootstrap5 %}


{% block title %}Wyszukaj klienta{% endblock %}

{% block content %}
<div class="search">
<div class='mb-3 mt-3'>
    <form method="GET" action="{% url 'orm:search_client' %}">
        {{ form.as_p }}
    {#        <button type="submit" class="button-33 ">Szukaj</button>#}
        {% bootstrap_button button_type="submit" content="Szukaj" %}

    </form>
</div>
    <div class='mb-3'>
        <a class='mb-3' href="{% url 'orm:client_list' %}" class="pb-3">{% bootstrap_button button_type="submit" content="Wróć do listy"  %}</a>
        {#{% bootstrap_button button_type="submit" content="Dodaj Klienta" %}#}
        {#<button role=button class="button-33 button-334 ">Wróć do listy</button>#}
    </div>
</div>

<section>
    <div >
         <table class="table table-striped">
            <thead>
                <tr class="table-success">
                    <th>ID Klienta</th>
                    <th>Nazwa Klienta</th>

                    <th>Adres</th>
                    <th>Dodany przez użytkownika</th>
                </tr>
            </thead>
            <tbody>
                {% if clients %}
                     {% for client in clients %}
                    <tr>
                        <td>
                            {{ client.id }}
                        </td>
                        <td>
                            <a href="{% url 'orm:client_page'  id=client.id slug=client.slug %}">
                                {{ client.name }}
                            </a>
                        </td>

                        <td>{{ client.address }}</td>
                        <td>{{ client.author }}</td>
                    </tr>
                {% endfor %}
            </tbody>
         </table>
                {% else %}
                    {% if 'query' in request.GET %}
                        <p>Brak wyników dla zapytania.</p>
                    {% endif %}
                {% endif %}
{#                    <a href="{% url 'orm:client_list' %}">Wróć do listy</a>#}
                  <a href="/" class="homepage"><img src="{% static 'images/back-arrow.png' %}"></a>
                {% endblock %}

templates/base.html
<!DOCTYPE html>
{% load static %}

<html lang="en">
<head>
   <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>
        {% block title %}
            Django App
        {% endblock %}
    </title>
    {% load django_bootstrap5 %}
    {%  bootstrap_css %}
    {% bootstrap_javascript %}
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <script src="{% static 'js/main.js' %}" defer></script>
   
</head>
<body>
    <nav class="navbar">
        <a href="/" title="Strona domowa"><img src="{% static 'images/home.png' %}"></a> ||
        {% if user.is_authenticated %}
            <a href="{% url 'orm:new-client' %}" title="Nowy Klient"><img src="{% static 'images/new-employee.png' %}"></a> |
            <a href="{% url 'orm:client_list' %}" title="Klienci"><img src="{% static 'images/rating.png' %}"></a> ||   
            <a href="{% url 'users_app:register' %}" title="Nowy użytkownik"><img src="{% static 'images/user.png' %}" alt="user icon"></a> | {# register#}
            <form class="logout" action="{% url 'users_app:logout' %}" method="post">
                {% csrf_token %}
    
                <button class="logout-button" title="Wyloguj"><img src="{% static 'images/exit-door.png' %}"></button>
            </form> |
            
        
        {% else %}
            <a href="{% url 'users_app:register' %}" title="Nowy użytkownik"><img src="{% static 'images/user.png' %}" alt="user icon"></a> | {# register#}
            <a href="{% url 'users_app:login' %}" title="Logowanie"><img src="{% static 'images/password.png' %}"></a> |   {# login#}        
        
        {% endif %}   &nbsp&nbsp&nbsp&nbsp__LIMS__project.blog
        <a href="/zlecenie" title="Dodaj zlecenie">Zlecenie od Klienta</a>
        <a href="/admin" title="Admin, czyli Ja" class="admin_logo"><img src="{% static 'images/software-engineer.png' %}"></a>  {# admin#}
    </nav>
    <main class="container">
        {% block content %}
        {% endblock %}

    </main>


</body>
</html>

templates/index.html
{% extends 'base.html' %}


{% block title %}
    Główna
{% endblock %}

{% block content %}
    <div class='p-5 text-center bg-body-tertiary rounded-3'>
    <h1 class="text-body-emphasis">Strona główna.</h1><br>
    <p class="col-lg-8 mx-auto fs-5 text-muted">Tu cos można wpisać i inne takie, ale glównie chodzi o to,
    żeby przejsc z tąd na inną strone.
    Na tej <a href="{% url 'orm:new-client' %}" class="text-decoration-none">podstronie</a> bedzie można wypełnć formularz dodania klienta
    z aplikacji LIMS. Takie początki nauki.
    A tu jeszcze <a href="{% url 'orm:client_list' %}" class="text-decoration-none">dalej</a> idziemy do listy Klientów</p>
    </div>
{% endblock %}

templates/orm.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
    Nowy Klient
{% endblock %}

{% block content %}
  <h1>Formularz dodania klienta</h1>
    <p><img src="{% static 'images/coffee-break.png' %}"></p>

    


    
   <a href="/" class="homepage"><img src="{% static 'images/back-arrow.png' %}"></a>
{% endblock %}

users_app/templates/users/login.html
{% extends 'base.html' %}
{% load static %}
{% load django_bootstrap5 %}



{% block title %}
   Logowanie
{% endblock %}

{% block content %}
    <div class="client">
        <h1>Logowanie</h1>
        <form class="form-with-validation register-form" action="{% url 'users_app:login' %}" method="POST">
{#            {% csrf_token %}#}
{#            {{ form.as_p }}#}
{#            {% if form.errors %}#}
{#                <ul>#}
{#                {% for field in form %}#}
{#                    {% for error in field.errors %}#}
{#                        <li>{{ field.label }}: {{ error }}</li>#}
{#                    {% endfor %}#}
{#                {% endfor %}#}
{#                {% for error in form.non_field_errors %}#}
{#                    <li>{{ error }}</li>#}
{#                {% endfor %}#}
{#                </ul>#}
{#            {% endif %}#}
{#            <button class="button-33" role="button" type="submit">Zarejestruj się</button>#}

            {% csrf_token %}
            {% bootstrap_form form %}
            {% if request.GET.next %}
                <input type="hidden" name="next" value="{{ request.GET.next }}"/>
            {% endif %}

{#            <button class="button-33" role="button">Zaloguj</button>#}
        {% bootstrap_button button_type="submit" content="Zaloguj" %}

        </form>
        <div class="client my-3">
            <a href="{% url 'users_app:register' %}">{% bootstrap_button button_type="button" content="Nowy użytkownik" %}</a>
{#            <button class="button-33" role="button">Nowy użytkownik</button>#}
        </div>
        <a href="/" class="homepage"><img src="{% static 'images/back-arrow.png' %}"></a>
    </div>

{% endblock %}

users_app/templates/users/register.html
{% extends 'base.html' %}
{% load static %}
{% load django_bootstrap5 %}


{% block title %}
   Rejestracja użytkowników
{% endblock %}

{% block content %}
    <div class="client ">
        <h1>Rejestracja</h1>
        <form class="form-with-validation register-form" action="{% url 'users_app:register' %}" method="POST">
{#            {% csrf_token %}#}
{#            {{ form.as_p }}#}
{#            {% if form.errors %}#}
{#                <ul>#}
{#                {% for field in form %}#}
{#                    {% for error in field.errors %}#}
{#                        <li>{{ field.label }}: {{ error }}</li>#}
{#                    {% endfor %}#}
{#                {% endfor %}#}
{#                {% for error in form.non_field_errors %}#}
{#                    <li>{{ error }}</li>#}
{#                {% endfor %}#}
{#                </ul>#}
{#            {% endif %}#}
{#            <button type="submit">Zarejestruj się</button>#}

            {% csrf_token %}
            {% bootstrap_form form %}
{#            <button class="button-33" role="button">Submit</button>#}
            {% bootstrap_button button_type="submit" content="Dodaj Użytkownika" %}
        </form>
        <a href="/" class="homepage"><img src="{% static 'images/back-arrow.png' %}"></a>
    </div>

{% endblock %}